name: wizardview
description: An extensible, dependency-free, focus-based implementation of Feature Discovery in Flutter
publish_to: "none"

version: 1.1.0

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
